### ISSUE TITLE
Add to Ansible Galaxy

### ISSUE THREAD

**Issue by bee-san** [shaderecker/ansible-pihole#12]
Hey! I'd love it if this could be added to ansible galaxy :)

**Comment by shaderecker** [comment]
Hi @bee-san, It's for sure something for consideration.
I've never developed roles for galaxy before, so I first have to get acquainted with that.

**Comment by shaderecker** [comment]
I currently don't find time for creating a galaxy role of this. If sb wants to contribute: Feel free!
