### ISSUE TITLE
Implement catch for IPv6 interface

### ISSUE THREAD

**Issue by shaderecker** [shaderecker/ansible-pihole#5]
As of #3 the playbook crashes when Ansible is not able to reach Google over IPv6 to determine the default IPv6 interface.
Implement a catch/default around `ansible_default_ipv6.interface` in the needed parts.

pihole role:
- https://github.com/shaderecker/ansible-pihole/blob/master/roles/pihole/tasks/main.yaml#L23

keepalive role:
- https://github.com/shaderecker/ansible-pihole/blob/master/roles/keepalived/templates/keepalived.j2#L41

Put sane default value (eth0) in `roles/pihole/defaults/main.yaml` & `roles/keepalived/defaults/main.yaml` (interface can be adjusted there if needed).

**Comment by shaderecker** [comment]
@relaxdiego I tested the fix in my setup with IPv6 enabled & disabled.
Now the playbooks run through in both cases.
Please verify if this suits your needs.

**Comment by relaxdiego** [comment]
Way better solution. Thanks, @shaderecker!
